### ISSUE TITLE
Express checkout with multiple sessions

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction-paypal#11]
When there are multiple sessions, same browser, using the express checkout some issues occur:
- invalid token errors from paypal
- invalid domain error from paypal
- leads to broken cartWorkflow state

seems to be fine during the first pass, it's after a second pass in the second session that things get screwy (so really an edge case)

**Comment by zenweasel** [comment]
This appears to be fixed as I can no longer reproduce.
