### ISSUE TITLE
Error calling paypal.checkout.setup() more than once

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction-paypal#16]
Investigate and resolve error with latest paypal updates:

`Error: You are calling paypal.checkout.setup() more than once. This function can only be called once per page load. Any further calls will be ignored.`

**Comment by hrath2015** [comment]
I got the exact same error today morning(09/24) on console. It stopped rendering the  Paypal express checkout Logo.

**Comment by aaronjudd** [comment]
@zenweasel to replicate:  checkout once with paypal express, then using same/user checkout once more, if no error in `client console`, and the order processes then this may been resolved in the recent paypal updates.

**Comment by zenweasel** [comment]
Cannot reproduce this error on the current `development` branch. Closing.

**Comment by zenweasel** [comment]
Accidentally happened upon this error while testing Payflow Pro. Not exactly replicated but it does seem to still be happening.

**Comment by zenweasel** [comment]
Have tested this **many**, **many** times and have not been able to reproduce during a normal checkout. Closing for now.

**Comment by zenweasel** [comment]
This bug has reappeared with the last round of updates. When you get this message it means that the Paypal Express button will not be rendered.

**Comment by newsiberian** [comment]
Hello. Maybe not the best place for this, but I've tested paypal payment via QupZilla - It shows some extra errors during the payment in my latest branch:
![paypal_qupzilla](https://cloud.githubusercontent.com/assets/11130487/12360674/2eefd9fc-bbdb-11e5-83bc-14606f7bc983.png)

**Comment by zenweasel** [comment]
I no longer can reproduce this bug. At one point it was happening every time. Closing until it pops up again because I don't think anyone else was seeing it.
