### ISSUE TITLE
PayPal BuyNow addresses in workflow

### ISSUE THREAD

**Issue by evliu** [reactioncommerce/reaction-paypal#7]
Looking at this, since PayPal will take care of the billing, there's no need for a Billing address selection, and since PayPal takes care of the shipping address and will return it on payment complete, we probably won't need their shipping address, although we do need to estimate the shipping cost.

We may also need to check that the shipping address they choose in PayPal matches what they choose on reaction after payment. Otherwise, as a user, I could estimate based on a locale that's much closer and cheaper, and on paypal checkout, put my actual address, which may actually cost a lot more than estimated.

I've been trying to think through this one, as I have no experience in this area. Thought I'd start a discussion that might be useful.

If Shipping Method would be all they needed to select on the checkout page, then I'll probably even integrate that into the cart drawer and have the checkout button go straight to paypal. Thoughts?

(All this applies to if PayPal BuyNow is the only checkout method where they don't need to select billing address, etc)

**Comment by bstocks** [comment]
I'm still running some tests, but it looks like we should be able to remove shipping address entirely from the paypal part of the flow. The user would just enter their shipping address in the reaction checkout flow and then the "pay with paypal" button would just walk them through signing into paypal and selecting a billing method. This would avoid the mis-matched shipping address issue you pointed out.

Interesting idea about having the checkout button in the cart drawer go straight to paypal. I've been trying to limit what the paypal button is doing to just payment of the total final amount, nothing to do with shipping. I know that frequent paypal users might like the convenience of using stored shipping addresses from their paypal account, but it seems simpler for now to keep shipping in reaction and only use the paypal button to process the money.

**Comment by evliu** [comment]
reference for all paypal buttons available
https://developer.paypal.com/docs/classic/api/buttons/

**Comment by evliu** [comment]
looking at https://developer.paypal.com/docs/classic/adaptive-payments/integration-guide/APIntro/ on section "Embedded Payment Flow Presentations", looks like you may be able to have the payment in a PayPal lightbox, which would keep it on the site.

![lightbox](https://www.paypalobjects.com/webstatic/en_US/developer/docs/ap/lightbox3.jpg)

**Comment by aaronjudd** [comment]
I think this should be closed now, as we're supporting express.  Also shipping methods (or other info)  cannot be changed once the payment workflow has begun (does nothing, console log error warning shown).
