### ISSUE TITLE
fails audit-argument-checks

### ISSUE THREAD

**Issue by evliu** [reactioncommerce/reaction-paypal#9]
```Exception while invoking method 'paypalSubmit' Error: Did not check() all arguments during call to 'paypalSubmit'```

**Comment by aaronjudd** [comment]
@evliu are you using the development branch?

**Comment by evliu** [comment]
yep

**Comment by aaronjudd** [comment]
@evliu Can you confirm if this was also resolved in reactioncommerce/reaction-core#111
I tested, but only "pro",  not the new paypal code.

**Comment by evliu** [comment]
fixed under aforementioned
